/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author camsq
 */
public class affichagejeu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(affichagejeu.class.getName());

    /**
     * Creates new form affichagejeu
     */
    public affichagejeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_excats = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        up_chiffre_7 = new javax.swing.JButton();
        up_chiffre_8 = new javax.swing.JButton();
        up_chiffre_6 = new javax.swing.JButton();
        up_chiffre_5 = new javax.swing.JButton();
        texte_chiffre_5 = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        texte_chiffre_6 = new javax.swing.JLabel();
        texte_chiffre_7 = new javax.swing.JLabel();
        down_chiffre_5 = new javax.swing.JButton();
        down_chiffre_6 = new javax.swing.JButton();
        down_chiffre_7 = new javax.swing.JButton();
        down_chiffre_8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouvez le bon code !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 14, -1, -1));

        texte_lbl_nb_chiffres_excats.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        texte_lbl_nb_chiffres_excats.setText("Nombre de chiffres exacts : ");
        getContentPane().add(texte_lbl_nb_chiffres_excats, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        texte_nb_chiffres_exacts.setText("NBR exact");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 70, -1));

        texte_lbl_nb_chiffres_haut.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts : ");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 21));

        texte_nb_chiffres_haut.setText("NBR hauts");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        texte_lbl_nb_chiffres_bas.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        texte_nb_chiffres_bas.setText("NBR bas");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 50, 20));

        texte_score.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        texte_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_score.setText("0 sur 5");
        texte_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 80, 40));

        texte_tentatives.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        texte_tentatives.setText("Tentatives :");
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        bouton_recommencer.setBackground(new java.awt.Color(255, 153, 255));
        bouton_recommencer.setText("Recommencer");
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        bouton_tester.setBackground(new java.awt.Color(255, 153, 255));
        bouton_tester.setText("Tester");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jPanel1.setLayout(new java.awt.GridLayout(3, 4, 40, 20));

        up_chiffre_7.setBackground(new java.awt.Color(204, 204, 204));
        up_chiffre_7.setText("/\\");
            up_chiffre_7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_7ActionPerformed(evt);
                }
            });
            jPanel1.add(up_chiffre_7);

            up_chiffre_8.setBackground(new java.awt.Color(204, 204, 204));
            up_chiffre_8.setText("/\\");
                jPanel1.add(up_chiffre_8);

                up_chiffre_6.setBackground(new java.awt.Color(204, 204, 204));
                up_chiffre_6.setText("/\\");
                    jPanel1.add(up_chiffre_6);

                    up_chiffre_5.setBackground(new java.awt.Color(204, 204, 204));
                    up_chiffre_5.setText("/\\");
                        jPanel1.add(up_chiffre_5);

                        texte_chiffre_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_5.setText("0");
                        texte_chiffre_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        jPanel1.add(texte_chiffre_5);

                        texte_chiffre_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_4.setText("0");
                        texte_chiffre_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        jPanel1.add(texte_chiffre_4);

                        texte_chiffre_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_6.setText("0");
                        texte_chiffre_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        jPanel1.add(texte_chiffre_6);

                        texte_chiffre_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        texte_chiffre_7.setText("0");
                        texte_chiffre_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                        jPanel1.add(texte_chiffre_7);

                        down_chiffre_5.setBackground(new java.awt.Color(204, 204, 204));
                        down_chiffre_5.setText("\\/");
                        jPanel1.add(down_chiffre_5);

                        down_chiffre_6.setBackground(new java.awt.Color(204, 204, 204));
                        down_chiffre_6.setText("\\/");
                        jPanel1.add(down_chiffre_6);

                        down_chiffre_7.setBackground(new java.awt.Color(204, 204, 204));
                        down_chiffre_7.setText("\\/");
                        jPanel1.add(down_chiffre_7);

                        down_chiffre_8.setBackground(new java.awt.Color(204, 204, 204));
                        down_chiffre_8.setText("\\/");
                        jPanel1.add(down_chiffre_8);

                        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 48, -1, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_7ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new affichagejeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_5;
    private javax.swing.JButton down_chiffre_6;
    private javax.swing.JButton down_chiffre_7;
    private javax.swing.JButton down_chiffre_8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_chiffre_5;
    private javax.swing.JLabel texte_chiffre_6;
    private javax.swing.JLabel texte_chiffre_7;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_excats;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_5;
    private javax.swing.JButton up_chiffre_6;
    private javax.swing.JButton up_chiffre_7;
    private javax.swing.JButton up_chiffre_8;
    // End of variables declaration//GEN-END:variables
}
