
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author camsq
 */
public class FenetreQuiz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());
    ArrayList<Question> questions = new ArrayList<>();
    private int indQC = 0;
    private int score = 0;

    private void afficherQuestionCourante() {
        Question q = questions.get(indQC);
        Label_Question.setText(q.getinti());

        btn_Rep1.setText(q.getp1());
        btn_Rep2.setText(q.getp2());
        btn_Rep3.setText(q.getp3());
        btn_Rep4.setText(q.getp4());

        btn_Rep1.setEnabled(true);
        btn_Rep2.setEnabled(true);
        btn_Rep3.setEnabled(true);
        btn_Rep4.setEnabled(true);

        Label_Bien.setVisible(false);
        Label_nul.setVisible(false);
        btn_qsuivant.setVisible(false);
    }

    /**
     ** Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();

        questions.add(new Question("Quelle est la capitale de l’Italie ?", "Rome", "Milan", "Venise", "Florence", 1));
        questions.add(new Question("Quelle est la capitale du Canada ?", "Toronto", "Ottawa", "Montréal", "Vancouver", 2));
        questions.add(new Question("Quelle est la capitale du Japon ?", "Kyoto", "Tokyo", "Osaka", "Nagoya", 2));
        questions.add(new Question("Quelle est la capitale de l’Australie ?", "Sydney", "Melbourne", "Canberra", "Brisbane", 3));
        questions.add(new Question("Quelle est la capitale du Brésil ?", "Rio de Janeiro", "São Paulo", "Brasília", "Salvador", 3));
        questions.add(new Question("Quelle est la capitale de l’Espagne ?", "Barcelone", "Madrid", "Séville", "Valence", 2));
        questions.add(new Question("Quelle est la capitale de l’Allemagne ?", "Berlin", "Munich", "Francfort", "Hambourg", 1));
        questions.add(new Question("Quelle est la capitale de la Russie ?", "Saint-Pétersbourg", "Moscou", "Novossibirsk", "Kazan", 2));
        questions.add(new Question("Quelle est la capitale de l’Égypte ?", "Alexandrie", "Le Caire", "Gizeh", "Louqsor", 2));
        questions.add(new Question("Quelle est la capitale de la Chine ?", "Shanghai", "Pékin", "Hong Kong", "Shenzhen", 2));

        afficherQuestionCourante();
    }

    private void verifRep(int numChoisi) {

        Question q = questions.get(indQC);

        if (numChoisi == q.getindBR()) {
            Label_Bien.setVisible(true);
            Label_nul.setVisible(false);

            score++;
            Label_score.setText("Score : " + score + "/10");
        } else {
            Label_Bien.setVisible(false);
            Label_nul.setVisible(true);
        }

        btn_Rep1.setEnabled(false);
        btn_Rep2.setEnabled(false);
        btn_Rep3.setEnabled(false);
        btn_Rep4.setEnabled(false);

        btn_qsuivant.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Question = new javax.swing.JLabel();
        btn_Rep1 = new javax.swing.JButton();
        btn_Rep2 = new javax.swing.JButton();
        btn_Rep3 = new javax.swing.JButton();
        btn_Rep4 = new javax.swing.JButton();
        Label_Bien = new javax.swing.JLabel();
        btn_qsuivant = new javax.swing.JButton();
        Label_nul = new javax.swing.JLabel();
        Label_score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Question.setText("Question");

        btn_Rep1.setText("Bouton1");
        btn_Rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Rep1ActionPerformed(evt);
            }
        });

        btn_Rep2.setText("Bouton2");
        btn_Rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Rep2ActionPerformed(evt);
            }
        });

        btn_Rep3.setText("Bouton3");
        btn_Rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Rep3ActionPerformed(evt);
            }
        });

        btn_Rep4.setText("Bouton4");
        btn_Rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Rep4ActionPerformed(evt);
            }
        });

        Label_Bien.setText("Bonne reponse ma star");

        btn_qsuivant.setText("jButton1");
        btn_qsuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qsuivantActionPerformed(evt);
            }
        });

        Label_nul.setText("Mauvaise reponse t'es nul");

        Label_score.setText("SCORE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_score)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_qsuivant))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_Rep1)
                                    .addComponent(btn_Rep3))
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_Rep4)
                                    .addComponent(btn_Rep2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_nul)
                                    .addComponent(Label_Bien)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(Label_Question, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(Label_Question, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Rep1)
                    .addComponent(btn_Rep2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Rep4)
                    .addComponent(btn_Rep3))
                .addGap(18, 18, 18)
                .addComponent(Label_Bien)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Label_score, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label_nul)
                        .addGap(36, 36, 36)
                        .addComponent(btn_qsuivant)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Rep3ActionPerformed
        VerifRep(3);
    }//GEN-LAST:event_btn_Rep3ActionPerformed

    private void btn_Rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Rep1ActionPerformed
        VerifRep(1);
    }//GEN-LAST:event_btn_Rep1ActionPerformed

    private void btn_Rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Rep2ActionPerformed
        VerifRep(2);
    }//GEN-LAST:event_btn_Rep2ActionPerformed

    private void btn_Rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Rep4ActionPerformed
        VerifRep(4);
    }//GEN-LAST:event_btn_Rep4ActionPerformed

    private void btn_qsuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qsuivantActionPerformed
        indQC++;

        if (indQC < 10) {

            afficherQuestionCourante();
        } else {
            Label_score.setText("Quiz terminé. Score : " + score + " / 10");

            btn_qsuivant.setEnabled(false);
        }
    }//GEN-LAST:event_btn_qsuivantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Bien;
    private javax.swing.JLabel Label_Question;
    private javax.swing.JLabel Label_nul;
    private javax.swing.JLabel Label_score;
    private javax.swing.JButton btn_Rep1;
    private javax.swing.JButton btn_Rep2;
    private javax.swing.JButton btn_Rep3;
    private javax.swing.JButton btn_Rep4;
    private javax.swing.JButton btn_qsuivant;
    // End of variables declaration//GEN-END:variables

    private void VerifRep(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
